-- P(R) represents a pattern drawn by Julia in R rows. The following pattern represents P(5):

-- * * * * * 
-- * * * * 
-- * * * 
-- * * 
-- *
-- Write a query to print the pattern P(20).

WITH RECURSIVE Pattern AS (
    SELECT 20 UNION ALL
    SELECT RowNum - 1 FROM Pattern
    WHERE RowNum > 1
)
SELECT REPEAT('* ', RowNum) AS Asterisks
FROM Pattern;



-- Explanation:
-- WITH RECURSIVE Pattern AS: This starts a recursive CTE named Pattern.
-- SELECT 20 AS RowNum: This initializes the CTE with the first row number, which is 20.
-- UNION ALL: This combines the initial row with the subsequent rows generated by the recursive part.
-- SELECT RowNum - 1 FROM Pattern WHERE RowNum > 1: This part of the CTE recursively subtracts 1 from the RowNum until it reaches 1.
-- SELECT REPEAT(' ', RowNum) AS Asterisks*: This selects the asterisks for each row, using the REPEAT function to create a string of asterisks followed by a space, based on the current RowNum.